apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: monitron-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "4"
        run.googleapis.com/cloudsql-instances: ${CLOUD_SQL_INSTANCE}
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT}
      containers:
        - image: ${API_IMAGE}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: DATABASE_URL
              value: ${DATABASE_URL}
            - name: REDIS_URL
              value: ${REDIS_URL}
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: access
            - name: JWT_REFRESH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: refresh
            - name: INITIAL_ADMIN_EMAIL
              value: ${INITIAL_ADMIN_EMAIL}
            - name: INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: initial-admin-password
                  key: password
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 4
