apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: monitron-web
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: ${WEB_IMAGE}
          ports:
            - containerPort: 8080
          env:
            - name: VITE_API_BASE_URL
              value: ${API_BASE_URL}
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
