apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: monitron-worker
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
        run.googleapis.com/cloudsql-instances: ${CLOUD_SQL_INSTANCE}
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT}
      containers:
        - image: ${WORKER_IMAGE}
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: DATABASE_URL
              value: ${DATABASE_URL}
            - name: REDIS_URL
              value: ${REDIS_URL}
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: access
            - name: JWT_REFRESH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: refresh
